// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtk9thMLvtDV6Knulflj2WJbm6OoyUF9Q',
    appId: '1:330568677451:web:9341152fbdd3b4ef62b5ce',
    messagingSenderId: '330568677451',
    projectId: 'todolist-82705',
    authDomain: 'todolist-82705.firebaseapp.com',
    storageBucket: 'todolist-82705.firebasestorage.app',
    measurementId: 'G-CXGPVZ73VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Pd0LUPuz_2nvcv00NnCY_ILXf-8XJgo',
    appId: '1:330568677451:android:cca8191b60e13d9162b5ce',
    messagingSenderId: '330568677451',
    projectId: 'todolist-82705',
    storageBucket: 'todolist-82705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Juuo5yKBJ2XVZYxGiL0zPhPvTy_XBYM',
    appId: '1:330568677451:ios:8a1b2829b2767b6962b5ce',
    messagingSenderId: '330568677451',
    projectId: 'todolist-82705',
    storageBucket: 'todolist-82705.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Juuo5yKBJ2XVZYxGiL0zPhPvTy_XBYM',
    appId: '1:330568677451:ios:8a1b2829b2767b6962b5ce',
    messagingSenderId: '330568677451',
    projectId: 'todolist-82705',
    storageBucket: 'todolist-82705.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtk9thMLvtDV6Knulflj2WJbm6OoyUF9Q',
    appId: '1:330568677451:web:0a1c7704abd9054d62b5ce',
    messagingSenderId: '330568677451',
    projectId: 'todolist-82705',
    authDomain: 'todolist-82705.firebaseapp.com',
    storageBucket: 'todolist-82705.firebasestorage.app',
    measurementId: 'G-1E996P0MQC',
  );
}
